### ISSUE TITLE
Stderr/Stdout data is a buffer, so when it's console.logged it's not as useful as a string

### ISSUE THREAD

**Issue by robfe** [claudiajs/pandoc-aws-lambda-binary#1]
AFAICT when we get data from the pandoc process's stdout/stderr streams, node is giving us a Buffer, which isn't so readable when passed to console.log. Please see my comment on the line in question, https://github.com/claudiajs/pandoc-aws-lambda-binary/commit/9464d99c71d710074d640b2162bd46be42089609#commitcomment-19144267

It would be helpful if we converted it to a string before console.logging it

Let me know if you'd like a PR

**Comment by gojko** [comment]
sure, submit a PR
