### ISSUE TITLE
tex2pdf conversion fails because it cannot create tempory directory

### ISSUE THREAD

**Issue by jhilden** [claudiajs/pandoc-aws-lambda-binary#4]
I tried to build a lambda function to create a PDF from a tex template.

And this is the output I'm getting:

```
> executing /tmp/pandoc in .
> pandoc: ./tex2pdf.-6d47e0bd3f553783: createDirectory: permission denied (Read-only file system)                                                         
```

This is the relevant code from my lambda function:

```
const pandoc = require('pandoc-aws-lambda-binary');
exports.lambdaHandler = async (event, context) => {
  const result = await pandoc('test_input.tex', '/tmp/test_output.pdf');
```

The issue seems that anything but the `/tmp` folder inside the lambda container is read-only.

Is there a way to tell pandoc to create its temp directory in `/tmp`?
Or is there a way to execute pandoc from `/tmp`?

**Comment by gojko** [comment]
pandoc executes in the directory of the input file by default (check https://github.com/claudiajs/pandoc-aws-lambda-binary/blob/master/src/pandoc.js) - so just put the input into tmp. the assumption was that you'll use this on lambda to process files sent/created at runtime anyway, so they will have to be in temp

**Comment by jhilden** [comment]
Thanks a lot for the quick response :green_heart:

This is exactly what I do now.  Before executing pandoc I do `cp ./test_input.tex /tmp/`, which does the trick.

However, now I had to discover that pandoc actually does not provide PDF conversion out-of-the-box:

```
pdflatex not found. Please select a different --pdf-engine or install pdflatex
```

Do you by chance have any tip for me how to get that binary into my lambda container?

**Comment by gojko** [comment]
this is the script I used on ec2 to produce the binary, you will likely want to modify the config somewhere to include the pdflatex library https://github.com/claudiajs/pandoc-aws-lambda-binary/blob/master/vendor/rebuild.sh
